name: Auto-merge Community Scenario PR
on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      error-message: ${{ steps.validation-step.outputs.error-message }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Action
        id: validation-step
        uses: mmusial/testaction/validate@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  pr-merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Merge PR
        uses: mmusial/testaction/pr-merge@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  pr-reject:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: validate
    if: failure()
    steps:
      - name: Close PR
        uses: mmusial/testaction/pr-reject@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message:  ${{ needs.validate.outputs.error-message }}